version: '3.7'

services:
  django:
    build: .
    environment: 
      SQL_ENGINE: ${SQL_ENGINE}
      SQL_NAME: ${SQL_NAME}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_HOST: ${SQL_HOST}
      SQL_PORT: ${SQL_PORT}
    command: python /app/src/manage.py runserver 0.0.0.0:8000
    user: 'devuser'
    volumes:
      - .:/app
    ports: 
      - 8000:8000
    depends_on: 
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@example.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    volumes:
      - pgadmin_data:/root/.pgadmin
    ports:
      - 5050:80
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
